/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clubes.view;

import clubes.model.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno
 */
public class TelaContratar extends javax.swing.JFrame {

    /**
     * Creates new form TelaContratar
     */
    public TelaContratar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pernaDominanteGr = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        tituloContrata = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        salario = new javax.swing.JLabel();
        salarioText = new javax.swing.JTextField();
        precoCompra = new javax.swing.JLabel();
        precoCompraText = new javax.swing.JTextField();
        tempoContrato = new javax.swing.JLabel();
        tempoContratoText = new javax.swing.JTextField();
        btnContratar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        valorVel = new javax.swing.JSpinner();
        velocidade = new javax.swing.JLabel();
        resistencia = new javax.swing.JLabel();
        posicaoOrigemText = new javax.swing.JTextField();
        valorRes = new javax.swing.JSpinner();
        posicaoOrigem = new javax.swing.JLabel();
        valorHab = new javax.swing.JSpinner();
        habilidade = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        pesoText = new javax.swing.JTextField();
        estatura = new javax.swing.JLabel();
        estaturaText = new javax.swing.JTextField();
        pernaDominante = new javax.swing.JLabel();
        pernaDominanteText = new javax.swing.JTextField();
        rescisao = new javax.swing.JLabel();
        rescisaoText = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratar Jogador");

        tituloContrata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloContrata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloContrata.setText("CONTRATAÇÃO");

        nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome.setText("Nome");

        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });

        salario.setText("Salário (R$)");

        precoCompra.setText("Preço de Compra");

        tempoContrato.setText("Meses de Contrato");

        btnContratar.setText("Contratar");
        btnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painel.setToolTipText("");
        painel.setName("Capacidades do jogador"); // NOI18N

        valorVel.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        velocidade.setText("Velocidade");

        resistencia.setText("Resistência");

        posicaoOrigemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoOrigemTextActionPerformed(evt);
            }
        });

        valorRes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        posicaoOrigem.setText("Posição de Origem:");

        valorHab.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        habilidade.setText("Habilidade");

        peso.setText("Peso");

        pesoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTextActionPerformed(evt);
            }
        });

        estatura.setText("Altura");

        estaturaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaturaTextActionPerformed(evt);
            }
        });

        pernaDominante.setText("Perna");

        pernaDominanteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pernaDominanteTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(posicaoOrigem)
                        .addGap(18, 18, 18)
                        .addComponent(posicaoOrigemText))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(habilidade)
                                    .addComponent(velocidade))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                                .addComponent(resistencia)
                                .addGap(18, 18, 18)))
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorHab)
                            .addComponent(valorVel)
                            .addComponent(valorRes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(peso)
                                    .addComponent(estatura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesoText, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(estaturaText)))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(pernaDominante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pernaDominanteText)))))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicaoOrigem)
                    .addComponent(posicaoOrigemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(velocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso)
                    .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorHab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habilidade)
                    .addComponent(estatura)
                    .addComponent(estaturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resistencia)
                    .addComponent(pernaDominante)
                    .addComponent(pernaDominanteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        rescisao.setText("Multa de rescisão");

        rescisaoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescisaoTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloContrata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnContratar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(precoCompra)
                                            .addComponent(salario)
                                            .addComponent(tempoContrato)
                                            .addComponent(rescisao))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tempoContratoText)
                                            .addComponent(salarioText, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(precoCompraText, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(rescisaoText))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloContrata)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salario)
                            .addComponent(salarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precoCompra)
                            .addComponent(precoCompraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempoContrato)
                            .addComponent(tempoContratoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rescisao)
                            .addComponent(rescisaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(btnContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed

    private void btnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarActionPerformed
        Connection conexao;
        try {
            conexao = Conexao.conecta();
            
            String sql = "INSERT INTO jogador(nome, peso, estatura, salario, validade_contrato, perna_dominante, velocidade, resistencia, habilidade, posicao, rescisao, precoCompra) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);";
            try (PreparedStatement stmt = conexao.prepareStatement(sql)) {
                stmt.setString(1, nomeText.getText());
                stmt.setDouble(2, Double.valueOf(pesoText.getText()));
                stmt.setDouble(3, Double.valueOf(estaturaText.getText()));
                stmt.setDouble(4, Double.valueOf(salarioText.getText()));
                stmt.setInt(5, Integer.valueOf(tempoContratoText.getText()));
                stmt.setString(6, pernaDominanteText.getText());
                stmt.setInt(7, (int) valorVel.getValue());
                stmt.setInt(8, (int) valorHab.getValue());
                stmt.setInt(9, (int) valorRes.getValue());
                stmt.setString(10, posicaoOrigemText.getText());
                stmt.setString(11, rescisaoText.getText());
                stmt.setString(12, precoCompraText.getText());
                stmt.executeUpdate();
                stmt.close();
            }
            
            conexao.close();
            nomeText.setText("");
            pesoText.setText("");
            estaturaText.setText("");
            salarioText.setText("");
            tempoContratoText.setText("");
            pernaDominanteText.setText("");
            valorHab.setValue(0);
            valorRes.setValue(0);
            valorVel.setValue(0);
            posicaoOrigemText.setText("");
            rescisaoText.setText(null);
            tempoContratoText.setText("");
            precoCompraText.setText("");
        } catch (SQLException ex) {
        System.out.println("Erro"+ex);
        } 
        
        
    }//GEN-LAST:event_btnContratarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        nomeText.setText("");
        pesoText.setText("");
        estaturaText.setText("");
        salarioText.setText("");
        tempoContratoText.setText("");
        pernaDominanteText.setText("");
        valorHab.setValue(0);
        valorRes.setValue(0);
        valorVel.setValue(0);
        posicaoOrigemText.setText("");
        rescisaoText.setText(null);
        tempoContratoText.setText("");
        precoCompraText.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void posicaoOrigemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoOrigemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoOrigemTextActionPerformed

    private void pesoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextActionPerformed

    private void estaturaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaturaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estaturaTextActionPerformed

    private void pernaDominanteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pernaDominanteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pernaDominanteTextActionPerformed

    private void rescisaoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescisaoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rescisaoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContratar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContratar;
    private javax.swing.JLabel estatura;
    private javax.swing.JTextField estaturaText;
    private javax.swing.JLabel habilidade;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeText;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel pernaDominante;
    private javax.swing.ButtonGroup pernaDominanteGr;
    private javax.swing.JTextField pernaDominanteText;
    private javax.swing.JLabel peso;
    private javax.swing.JTextField pesoText;
    private javax.swing.JLabel posicaoOrigem;
    private javax.swing.JTextField posicaoOrigemText;
    private javax.swing.JLabel precoCompra;
    private javax.swing.JTextField precoCompraText;
    private javax.swing.JLabel rescisao;
    private javax.swing.JTextField rescisaoText;
    private javax.swing.JLabel resistencia;
    private javax.swing.JLabel salario;
    private javax.swing.JTextField salarioText;
    private javax.swing.JLabel tempoContrato;
    private javax.swing.JTextField tempoContratoText;
    private javax.swing.JLabel tituloContrata;
    private javax.swing.JSpinner valorHab;
    private javax.swing.JSpinner valorRes;
    private javax.swing.JSpinner valorVel;
    private javax.swing.JLabel velocidade;
    // End of variables declaration//GEN-END:variables
}
